# playbook.yml
- name: deploy backend to host
  hosts: backend

  tasks:
  - name: checkout backend code on host
    git:
      repo: git@github.com:And0r-/MatrixRegisterBackend.git
      dest: ~/projects/MatrixRegisterBackend

  - name: build docker image
    become: true
    docker_image:
      name: matrix_register_backend
      build:
        path: /home/andreas/projects/MatrixRegisterBackend
      source: build
      state: present
      force_source: yes
      debug: yes
      buildargs:
        MATRIX_CREATE_TOKEN: "{{MATRIX_BOT_PASSWORD}}"
        MATRIX_BOT_USER: "{{MATRIX_BOT_USER}}"
        MAIL_PASSWORD: "{{MAIL_PASSWORD}}"

  - name: restart docker image
    become: true
    docker_container:
      name: matrix_register_backend
      image: matrix_register_backend
      env:
        MATRIX_CREATE_TOKEN: "{{MATRIX_BOT_PASSWORD}}"
        MATRIX_BOT_USER: "{{MATRIX_BOT_USER}}"
        MAIL_PASSWORD: "{{MAIL_PASSWORD}}"
      recreate: yes
      ports:
        - "49171:3001"
      restart: yes
      restart_policy: always
      volumes:
        - "/home/andreas/projects/MatrixRegisterBackend/data:/app/data"
